### ISSUE TITLE
where is get_trigger defined? 

### ISSUE THREAD

**Issue by kilimchoi** [CityOfZion/neo-ruby#10]
Is this library incomplete or am I just not finding the method definition?

**Comment by kilimchoi** [comment]
Following up, but it seems like a lot of methods are just raising `NotImplementedError` in `interop.rb` Should there be TODO in the comments?

**Comment by ambethia** [comment]
The `NotImplementedError` really a TODO list right now. Like the README says, this is still under heavy development and not everything is complete.
