### ISSUE TITLE
CI server - CircleCI vs Travis

### ISSUE THREAD

**Issue by nunosilva800** [CityOfZion/neo-ruby#5]
Since the merge with ruby-sdk repo, we now have two CI services running: CircleCI and Travis.

I believe it's better to have only one.
Any preference?

**Comment by ambethia** [comment]
Yes, I think Travis. I thought I turned it off on Circle. Maybe I only turned off the old repo on Travis.

**Comment by ambethia** [comment]
Ok, disabled Circle, and I'm about to remove the config now. I believe I already removed the circle related gems from the test suite.
